import React from 'react'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/styles/globals.scss'
import Providers from '@/app/providers'
import { Params, ParamsLng } from '@/types/params'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: ['Next.js', 'React', 'JavaScript'],
  icons: {
    icon: [
      {
        url: '/icon.ico', // /public path
        href: '/icon.ico', // /public path
      },
    ],
  },
}

interface IRootLayout extends Params {
  children: React.ReactNode
}

export default async function RootLayout({ children, params: { locale } }: IRootLayout) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  )
}
