import React from 'react'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/styles/globals.scss'
import Providers from '@/app/providers'
import { Params, ParamsLng } from '@/types/params'
import { getTranslationServer } from '@/i18n/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
  keywords: ['Next.js', 'React', 'JavaScript'],
  // icons: {
  //   icon: [
  //     {
  //       url: '/icon.ico', // /public path
  //       href: '/icon.ico', // /public path
  //     },
  //   ],
  // },
}

interface IRootLayout extends Params {
  children: React.ReactNode
}

export default async function RootLayout({ children, params: { locale } }: IRootLayout) {
  const { t } = await getTranslationServer(locale)
  metadata.title = `${t('title-web')}`
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers locale={locale}>{children}</Providers>
      </body>
    </html>
  )
}
